java_binary(
    name = "LogTest",
    srcs = ["LogTest.java"],
    resources = ["//src/main/resources"],
    visibility = ["//visibility:public"],
    deps = [
        "@maven//:org_slf4j_slf4j_api",
        "@maven//:org_slf4j_slf4j_jdk14",
        "@maven//:com_google_cloud_google_cloud_logging",
    ],
)

